# app/config/routing.yml


# partie public
rubens_web:
    resource: "@RubensWebBundle/Resources/config/routing.yml"
    prefix:   /
    
#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media    

# partie LOGIN
rubens_security_login:
    pattern: /login
    defaults: { _controller: RubensCoreBundle:Security:login }

# partie spécifique
RubensCoreBundle_post:
        resource: "@RubensCoreBundle/Resources/config/routing/post.yml"
        prefix:   /post

RubensCoreBundle_image:
        resource: "@RubensCoreBundle/Resources/config/routing/image.yml"
        prefix:   /image

RubensCoreBundle_categorie:
        resource: "@RubensCoreBundle/Resources/config/routing/categorie.yml"
        prefix:   /categorie

RubensCoreBundle_utilisateur:
        resource: "@RubensCoreBundle/Resources/config/routing/utilisateur.yml"
        prefix:   /utilisateur

RubensCoreBundle_video:
        resource: "@RubensCoreBundle/Resources/config/routing/video.yml"
        prefix:   /video

RubensCoreBundle_document:
        resource: "@RubensCoreBundle/Resources/config/routing/document.yml"
        prefix:   /document



# partie FOSUSER
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
# partie indépendante des bundles
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
