# app/config/security.yml

security:
    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512
        Rubens\CoreBundle\Entity\Utilisateur: sha512
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_MEMBER:    ROLE_USER
        ROLE_ADMIN:      ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MEMBER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false

        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                csrf_parameter: _csrf_token
                default_target_path: rubens_admin_homepage
                username_parameter: _username
                password_parameter: _password
                remember_me : true
            remember_me:
                key: "%secret%"
                lifetime: 3600
                path: /
                domain: ~
            logout:       true
            anonymous:    true
            switch_user : true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_ADMIN }
        - { path: ^/elfinder, role: ROLE_ADMIN }
