parameters:
#    rubens_web.example.class: Rubens\WebBundle\Example

services:
#    rubens_web.example:
#        class: %rubens_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
